### ISSUE TITLE
lights can't be added

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.lifx#1]
When I try to add a light (can be controlled through android-app of lifx) Homey (on 0.8.32) switches from "follow the instructions" to "no new lights found" within a second. According to
https://forum.athom.com/discussion/1082/solved-lifx-app-doesnt-find-bulbs
I should do a recovery with clean install but that's too much I guess. Zwave, Kaku etc running fine...

**Comment by bvdbos** [comment]
guess it took some rebooting, works for me now. I didn't do a recovery with clean start.

**Comment by RobinBol** [comment]
Great that it works now, was looking at it the other day, but it's rather difficult to debug as of course when testing all LIFX bulbs are found (otherwise it would get passed our quality check).
