### ISSUE TITLE
Trigger card changed dim-level does not work

### ISSUE THREAD

**Issue by jghaanstra** [athombv/com.lifx#10]
**What is your Homey version (Settings → System)?**
firmware 1.1.12 / LIFX app 2.0.4

**What did you try to achieve?**
Trigger a flow when the dim level of a LIFX bulb is changed with the "changed dim-level" action card.

**Please include detailed steps how we can reproduce the issue**
Create a flow with the "changed dim-level" action card, for instance one that sends a push message to your phone with the new dim-level. Then change the dim-level through the device.

**What was the result?**
The flow was not triggered.

**What did you expect as result?**
That the flow with the action card "changed dim-level" action card would be triggered as the dim-level of the LIFX bulb was changed.

**Comment by RobinBol** [comment]
Hi! Did you change the dim level using the mobile-card or via a Flow? Or did you use the official Lifx smartphone app for that?

**Comment by jghaanstra** [comment]
I used the "changed dim-level" action card in a flow to change the dim level. Just tested it again and now the trigger card does work. So it seems to be fixed now. It also work when controlling the LIFX lamp in Homey directly. It does not work when using the official LIFX app but I understand why this is not working as Homey would probably need to poll the bulb. I'm closing this as the initial submitted bug does not exist anymore.
