### ISSUE TITLE
LIFX app looses connections with the bulbs often

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/com.lifx#12]
I have the beta version (v2.0.6) of the LIFX app installed which works great for syncing the status of the LIFX lights. However, it often looses connection with the bulbs which requires a restart of the app. One time the LIFX app even crashed (don't know if this has the same root cause). I tried to send an bug reports but I don't think that worked correctly.

**Comment by jprgomet** [comment]
+1
it losses connection a lot but I don't need to restart the app, just wait few moments and its back, then lost again ...

**Comment by WeeJeWel** [comment]
Should be fixed since the rewrite
