### ISSUE TITLE
Feature request: Fade in / out on brightness change

### ISSUE THREAD

**Issue by jprgomet** [athombv/com.lifx#13]
**The current situation.**
In a flow when I change brightness it is moved in a second, jump from 50% to 100%.

**A detailed proposal or pull request that demonstrates how the problem could be solved.**
Make any change in brightness faded?

**A use case – who needs this feature and why?**
Any one that uses LIFX.

**Comment by WeeJeWel** [comment]
Fixed in the rewrite
