### ISSUE TITLE
Turning on a multi colored Lifx Z forces it to white

### ISSUE THREAD

**Issue by moekdegroot** [athombv/com.lifx#15]
Hi @WeeJeWel ,

If you power a multi colored lifx z off and then on again it's turn to white instead off returning to its previous state.
If you turn it off and on again with the original lifx app the  multi colors are maintained.
If the strip is a single color it does not occure.

**Comment by WeeJeWel** [comment]
Thank you. We will receive our strip shortly, I will then try to fix the issue.

**Comment by moekdegroot** [comment]
Cool, thx Emile!
You’re gonna like them :)
