### ISSUE TITLE
Feature request: use the lan api instead of the cloud api

### ISSUE THREAD

**Issue by moekdegroot** [athombv/com.lifx#17]
Is this also a possibility because the difference between the two is significant.
Via the cloud takes a second or two, using lan (with the official ap) is almost instant.
Enough for my wife to start pressing buttons before the changes are applied ;)

**Comment by JesperJanssen** [comment]
I can confirm that it indeed takes some seconds before the LIFX lights react on the command. With the old version it used to be almost instant.

**Comment by WeeJeWel** [comment]
We have moved away from the LAN Api because it was very unstable. The cloud API is indeed a little bit slower, but it comes with greater reliability.
