### ISSUE TITLE
Feature request: add lifx z zones

### ISSUE THREAD

**Issue by moekdegroot** [athombv/com.lifx#19]
Like the title says it would be great to the be able to control the different zones in a lifx z strip.
Especially being able to control the brightness of a zone would be awesome so you can create some sort of spotlight lighting.
You mentioned you could maybe add zone support in a flow but that could mean a lot off cards to control a strip.
1 meter strip contains 8 zones so 2 off my strips (of 4 meters length ) would require 32 cards just to change the brightness.
64 if I also want to change the color.
So if there's any way to implement it in another way... ;)

**Comment by WeeJeWel** [comment]
Fixed

**Comment by WeeJeWel** [comment]
Please re-pair the strip with version 3.1.1
