### ISSUE TITLE
relative value control

### ISSUE THREAD

**Issue by arnodeclercq** [athombv/com.lifx#2]
Would it be possible to integrate the option to relatively change the value of hue, saturation, brightness and temperature. For example; add 5 % brightness.
Right now you can only switch on/off or set an absolute value.
This would allow to have the same control like the wheels in the native lifx app with a physical dimmer/switch. Thanks

**Comment by RobinBol** [comment]
You mean from a flow? This is something that should/could be added for all light devices. Not specific to LIFX, this will therefore not be added to this app.

**Comment by arnodeclercq** [comment]
Yes, from a flow. 
Where should this feature be request if not here?

**Comment by RobinBol** [comment]
https://github.com/athombv/homey/issues
