### ISSUE TITLE
Feature Request: Add Polling

### ISSUE THREAD

**Issue by moekdegroot** [athombv/com.lifx#4]
Hi@RobinBol ,
Would it be possible to add polling to the Lifx app just like in the hue app?
Maybe every 20,30 seconds or something?
Homey now doesn't know when a light is turned on or off if someone uses the official lifx-app.
Thx!

**Comment by RobinBol** [comment]
For now I will close this issue, to replace it with #6.

**Comment by moekdegroot** [comment]
Thx robin
