### ISSUE TITLE
Feature request: lifx z zone support

### ISSUE THREAD

**Issue by moekdegroot** [athombv/com.lifx#7]
It would be great if zone support for the lifx z strips could be added. 
Thanks!

**Comment by moekdegroot** [comment]
Hi @RobinBol , just in case you missed it:
https://github.com/MariusRumpf/node-lifx/pull/53#event-922774587
I hope you find the time to implement this in the homey app.
Thanks, Moek

**Comment by RobinBol** [comment]
Thanks for the heads up, I've put it on my to do list!

**Comment by RobinBol** [comment]
Btw, would you like the zones to be added to Homey as separate devices? I guess that's the most useful way, then you'll have one main node (the whole strip) and X sub nodes representing the zones?

**Comment by moekdegroot** [comment]
That sounds great! 
So if I understand correctly I can change to an overall color/brightnes using the main node and have separate color control every 25 cm using the subnodes?
Awsome!
I'm also hoping that not just the color but also the brightness will be controllable using the subnodes. 
That's the main reason I bought the strips, to create "spotlight" light effect presets and not having to wash the entire wall with color. 
Fingers crossed! :)
Thanks a lot Robin!

**Comment by RobinBol** [comment]
Well that is my idea, have to dive into the api to see what is possible, and preferably test it on the device itself. So can not give you an ETA but it is on my to do list!

**Comment by moekdegroot** [comment]
Sounds great robin!
If you need anything tested, let me know. 
I'm in the middle of installing 12 meters along the walls as we speak :)
Oh, and I read somewhere that status of the bulbs (and i guess also the strips) can be read through an api key and lifx's cloud. 
I'll try to find the links and post them in the issue you created last year. 

Thanks again!
Moek

**Comment by lubbertkramer** [comment]
Any news on this? I want to buy some but otherwise i start with one to look if i can support it myself, if Athom will support it i will order a larger badge :)

**Comment by RobinBol** [comment]
Not yet high on my to do list, so feel free to try and support it yourself. Should be fairly similar to the drivers of the bulbs!

**Comment by WeeJeWel** [comment]
Fixed
