### ISSUE TITLE
Feature request: In-/decrease intensity over time

### ISSUE THREAD

**Issue by kruimel0** [athombv/com.lifx#8]
I believe the gentle increase/decrease of the light intensity is currently added as a certain time (0.5-1 seconds). Could more freedom over this be added as another variable in the 'change intensity' card?

I believe this was well-documented in LIFX's API (and it's possible with their IFTTT integration).

**Comment by RobinBol** [comment]
You mean dimming or fading the lights over a larger period of time? Say 5 minutes?

**Comment by kruimel0** [comment]
That's indeed what I mean; hopefully with user-definable time periods instead of a drop-down menu. Good to hear that this will come :)

**Comment by RobinBol** [comment]
Will close this issue now as it is not related to the lifx app. Support for this is on the roadmap though!
