### ISSUE TITLE
Changing brightness changes temperature/colour

### ISSUE THREAD

**Issue by arnodeclercq** [athombv/com.lifx#9]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Using a flow to change the brightness of an lifx light.
I expect it to change like it would when I use the scroller in the lifx app.
However it changes colour and temperature, not brightness.

![flowlifx](https://cloud.githubusercontent.com/assets/1454216/21620597/6d362028-d1f5-11e6-8de7-5f171e9ab382.jpg)

Before running flow
![screenshot_20170103-203318](https://cloud.githubusercontent.com/assets/1454216/21620797/57282d0c-d1f6-11e6-84ed-e0d4526fe325.png)
After
![screenshot_20170103-203339](https://cloud.githubusercontent.com/assets/1454216/21620801/5aaa86f0-d1f6-11e6-9e6c-ff9db7758a95.png)
Before
![screenshot_20170103-203742](https://cloud.githubusercontent.com/assets/1454216/21620809/611d4112-d1f6-11e6-904b-1ab5d3326f0f.png)
After
![screenshot_20170103-203800](https://cloud.githubusercontent.com/assets/1454216/21620813/63433956-d1f6-11e6-96d6-06b7ab047258.png)

**What was the result?**
Changes colour / temperature instead of only brightness

**What did you expect as result?**
Only change brightness

**Comment by RobinBol** [comment]
As long as you do not use the Lifx smartphone app this should not happen, see https://github.com/athombv/com.lifx/issues/5

**Comment by arnodeclercq** [comment]
Ok, sorry about that, didn't see the closed issue.
Thanks!

**Comment by RobinBol** [comment]
This issue will be continued here: https://github.com/athombv/com.lifx/issues/6
